name: snowflake-devops-demo2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
     - main
    paths:
     - 'dbscripts/**'
     
  workflow_dispatch:

jobs:
 deploy-Snowflake-changes-job:
   runs-on: ubuntu-latest
   steps:
       - name: Setup Python 3.8.x
         uses: actions/setup-python@v2.2.1
         with:
           python-version: 3.8.x
 
       
       - name: Run schemachange
       
         env: 
          SNOWFLAKE_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SF_USERNAME }}
          SNOWFLAKE_ROLE: ${{ secrets.SF_ROLE }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SNOWFLAKE_WH: ${{ secrets.SF_WAREHOUSE }}
          SNOWFLAKE_DB: ${{ secrets.SF_DATABASE }}
         run: |
           pip install schemachange
           schemachange -f ${GITHUB_WORKSPACE}/snowflake_objects -a     $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USER -r $SNOWFLAKE_ROLE -w $SNOWFLAKE_WH -c $SNOWFLAKE_DB.METADATA.CHANGE_HISTORY — var $SCHEMACHANGE_VAR
           
